---
- name: Installiere ondrej/php repository
  apt_repository:
    repo: ppa:ondrej/php
    
- name: Installiere PHP Version 7.2
  apt:
    name: "{{ packages }}"
    update-cache: yes
  vars:
    packages:
      - php7.2-bz2
      - php7.2-cli
      - php7.2-common
      - php7.2-curl
      - php7.2-fpm
      - php7.2-gd
      - php7.2-gmp
      - php7.2-intl
      - php7.2-json
      - php7.2-mysql
      - php7.2-mbstring
      - php7.2-xml
      - php7.2-zip
      - php-imagick
      - libapache2-mod-fcgid
      
- name: Aktiviere Apache Proxy module
  shell: a2enmod proxy && a2enmod proxy_fcgi
     
- name: Aktiviere Apache PHP-FPM Konfiguration
  shell: a2enconf php7.2-fpm
  notify: restart apache2