---
- name: Installiere ownCloud
  get_url:
    url: https://download.owncloud.org/community/owncloud-10.1.1.tar.bz2
    checksum: 'sha256:https://download.owncloud.org/community/owncloud-10.1.1.tar.bz2.sha256'
    dest: /root/owncloud-10.1.1.tar.bz2

- name: Entpacke Archiv
  unarchive:
    src: /root/owncloud-10.1.1.tar.bz2
    remote_src: yes
    dest: /var/www/html
    owner: www-data
    group: www-data

- name: Erstelle data Verzeichnis
  file:
    path: /var/www/html/data
    state: directory
    owner: www-data
    group: www-data

- name: Generiere ein neues Passwort
  shell: openssl rand -base64 96 | tr -cd '[:alnum:]' | cut -c -24
  register: mysql_password

- name: Erstelle eine neue Datenbank mit dem Namen 'ocloud'
  mysql_db:
    name: ocloud
    state: present

- name: Erstelle Datenbank und Benutzer
  mysql_user:
    name: 'ocdbuser'
    host: localhost
    password: '{{ mysql_password.stdout }}'
    priv: 'ocloud.*:ALL'
    state: present

- name: Generiere ein neues ocadmin Passwort
  shell: openssl rand -base64 96 | tr -cd '[:alnum:]' | cut -c -24
  register: oc_admin_pw

- name: Gieb das Admin Passwort aus
  debug:
      msg: "Speicher das folgende ownCloud-Password für Benutzer ocadmin im Keypass: {{ oc_admin_pw.stdout }}"

- name: Installiere owncloud mit occ
  shell: >
    sudo -u www-data \
    php ./occ \
    maintenance:install \
    --database mysql \
    --database-name="ocloud" \
    --database-user="ocdbuser" \
    --database-pass="{{ mysql_password.stdout }}" \
    --admin-user="ocadmin" \
    --admin-pass="{{ oc_admin_pw.stdout }}" \
    --data-dir="/var/www/html/data"
  args:
    chdir: /var/www/html/owncloud

- name: Aktiviere Apache headers module
  shell: a2enmod headers
  notify: restart apache2

- name: Kopiere Virtual host von template
  template:
    src: domain_name.conf.j2
    dest: /etc/apache2/sites-available/{{ domain_name }}.conf
    owner: root
    group: root
    mode: 0600

- name: aktiviere Virtual host
  shell: a2ensite "{{ domain_name }}"
  notify: restart apache2

- name: deaktiviere default sites
  shell: a2dissite 000-default
  notify: restart apache2

- name: Installiere trusted domain fuer owncloud mit occ
  shell: >
    sudo -u www-data \
    php ./occ \
    config:system:set \
    trusted_domains 1 \
    --value="{{ domain_name }}"
  args:
    chdir: /var/www/html/owncloud

